#include <gtest/gtest.h>

#include "security/Permissions.hpp"

#include <vector>

TEST(Permissions, ClassifiesExternallyRequestablePermissions) {
    EXPECT_FALSE(Security::isExternallyRequestablePermission(HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_UNOBTAINIUM));
    EXPECT_FALSE(Security::isExternallyRequestablePermission(HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_TAVERNKEEP));
    EXPECT_TRUE(Security::isExternallyRequestablePermission(HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_SETTINGS_WALLPAPER));
    EXPECT_FALSE(Security::isKnownPermission(999999));
}

TEST(Permissions, ResolvesPermissionImplication) {
    EXPECT_TRUE(Security::permissionImplies(HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_SETTINGS, HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_SETTINGS_WALLPAPER));
    EXPECT_TRUE(Security::permissionImplies(HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_SETTINGS_BASIC, HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_SETTINGS_WALLPAPER));
    EXPECT_FALSE(
        Security::permissionImplies(HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_SETTINGS_BASIC, HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_SETTINGS_MANAGE_SECRETS));
    EXPECT_FALSE(Security::permissionImplies(HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_TAVERNKEEP, HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_UNOBTAINIUM));
}

TEST(Permissions, SanitizesExternalPermissionLists) {
    const auto sanitized = Security::sanitizeExternalPermissions({
        HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_TAVERNKEEP,
        HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_SETTINGS_WALLPAPER,
        HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_SETTINGS_WALLPAPER,
        999999,
    });
    const auto expected = std::vector<uint32_t>{HP_HYPRTAVERN_CORE_V1_SECURITY_PERMISSION_TYPE_SETTINGS_WALLPAPER};

    EXPECT_EQ(sanitized, expected);
}
